ThatConference/that-api-sessions

.env.sample
.vscode/settings.json
package-lock.json
package.json
src/graphql/index.js
src/index.js

Story details: https://app.clubhouse.io/thatconference/story/1506

Add sentry

---

src/graphql/resolvers/queries/index.js
src/graphql/resolvers/queries/sessions.js
src/graphql/typeDefs/queries/sessions.graphql
src/graphql/typeDefs/schema.graphql

Story details: https://app.clubhouse.io/thatconference/story/1513

create the base schema across all services

---

package-lock.json
package.json
src/index.js

Adds express cors to the middlware stack.
closes issue #5

adds cors to the middleware stack

---

src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/mutations/root.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js
src/graphql/resolvers/queries/root.js
src/graphql/resolvers/queries/sessions.js
src/graphql/typeDefs/dataTypes/session.graphql
src/graphql/typeDefs/dataTypes/sessionInput.graphql
src/graphql/typeDefs/mutations/session.graphql
src/graphql/typeDefs/mutations/sessions.graphql
src/index.js

Enables the following:
* Create a new session
* Update a session

enables create and update

---

package-lock.json
package.json
src/dataSources/cloudFirestore/session.js
src/envConfig.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js
src/index.js

* adds a reference to postmark
* caches the postmark client at the server instance
* adds postmark to the datasources context
* sends email on update. will be updated later.

adds the initial cut of sending a confirmation email

---

src/dataSources/cloudFirestore/session.js

Adds a check to make sure the user requesting the document update is a user listed on the document.

user enforcement

---

src/dataSources/cloudFirestore/session.js
src/graphql/typeDefs/dataTypes/session.graphql
src/graphql/typeDefs/dataTypes/sessionInput.graphql

Removes the member fields from sessions.

updates schema fields

---

src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/queries/sessions.js
src/graphql/typeDefs/queries/sessionsQuery.graphql

Will return all sessions for your you
example query
```
query getMySessions {
sessions {
me {
id
title
}
}
}
```

Fulfills the me session query

---

src/dataSources/cloudFirestore/session.js
src/graphql/typeDefs/dataTypes/artifact.graphql
src/graphql/typeDefs/dataTypes/artificatInput.graphql
src/graphql/typeDefs/dataTypes/enums/category.graphql
src/graphql/typeDefs/dataTypes/enums/mentorship.graphql
src/graphql/typeDefs/dataTypes/enums/status.graphql
src/graphql/typeDefs/dataTypes/enums/targetAudience.graphql
src/graphql/typeDefs/dataTypes/session.graphql
src/graphql/typeDefs/dataTypes/sessionInput.graphql

* Adds Session Status
* Secondary Category is now an array
* isCancelled is gone.
* adds overall category

overall schema updates

---

.github/workflows/pushMasterCi.yml
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js

Postmark called commented out until the rest of the data is available to send to template so no "BAD" emails go to real people.
Leaving TemplateId there, commented out in case there is an issue with using alias

add transaction emails + reformat version

---

src/dataSources/cloudFirestore/member.js
src/events/user.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js
src/index.js

* adds the user lookup
* refactors to event based notifications

refactors user notificatoins to event based

---

src/dataSources/cloudFirestore/member.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js
src/graphql/typeDefs/dataTypes/enums/status.graphql

updates email flow based on status

---

.eslintrc
package-lock.json
package.json
src/dataSources/cloudFirestore/session.js
src/graphql/index.js
src/graphql/resolvers/queries/session.js
src/graphql/typeDefs/dataTypes/session.graphql
src/graphql/typeDefs/extended-Profile.graphql
src/graphql/typeDefs/extended-PublicProfile.graphql

* Adds Data Loader
* Resolves Reference for Sessions
* Swaps over to public profile

enables resolving federated sessions

---

src/dataSources/cloudFirestore/voting.js
src/graphql/resolvers/mutations/index.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessions.js
src/graphql/resolvers/mutations/voting.js
src/graphql/typeDefs/dataTypes/vote.graphql
src/graphql/typeDefs/dataTypes/voteInput.graphql
src/graphql/typeDefs/mutations/session.graphql
src/graphql/typeDefs/mutations/sessions.graphql
src/graphql/typeDefs/mutations/voting.graphql

`mutation castVote ($eventId: ID!, $vote: VoteInput!) {
sessions {
voting(eventId: $eventId) {
cast(vote: $vote){
id
notes
memberId
}
}
}
}
`

adds cast voting mutation

---

src/dataSources/cloudFirestore/voting.js
src/graphql/resolvers/queries/anonymizedSession.js
src/graphql/resolvers/queries/index.js
src/graphql/resolvers/queries/voting.js
src/graphql/typeDefs/queries/votingQuery.graphql

```
query getVotedSessions ($eventId: ID!) {
sessions {
me {
voting(eventId: $eventId){
isVotingOpen
totalSubmitted
voted {
id
title
longDescription
takeaways
}
}
}
}
}
```

adds voting review list

---

src/graphql/resolvers/queries/voting.js
src/lib/shuffle.js

will now shuffle sessions to be voted on.

shuffles sessions

---

src/dataSources/cloudFirestore/session.js
src/graphql/index.js
src/graphql/resolvers/queries/voting.js

* fixes dataloader order reference
* fixes orphaned votes

updating dataloader for order and orphanded data

---

src/dataSources/cloudFirestore/voting.js

Adds the following:
* createdAt on a voteCast
* lastModifiiedAt on every voteCast

adds createdAt and lastUpdatedAt on a vote

---

src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/queries/voting.js

updates totals just for professional.

updates totals count

---

package-lock.json
package.json
src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/index.js
src/graphql/typeDefs/dataTypes/enums/status.graphql
src/graphql/typeDefs/dataTypes/session/acceptedSession.graphql
src/graphql/typeDefs/dataTypes/session/anonymizedSession.graphql
src/graphql/typeDefs/dataTypes/session/mySession.graphql
src/graphql/typeDefs/scalars.graphql

Slug genderated on session create. ID used for slug if slug is duplicate

Add session slug [ch1942]

---

src/dataSources/cloudFirestore/member.js
src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/mutations/adminSession.js
src/graphql/resolvers/mutations/adminSessionCreate.js
src/graphql/resolvers/mutations/adminSessionUpdate.js
src/graphql/resolvers/mutations/adminSessions.js
src/graphql/resolvers/mutations/index.js
src/graphql/resolvers/mutations/session.js
src/graphql/resolvers/mutations/sessionUpdate.js
src/graphql/resolvers/mutations/sessions.js
src/graphql/typeDefs/dataTypes/keynoteAdminInput.graphql
src/graphql/typeDefs/dataTypes/openSpaceAdminInput.graphql
src/graphql/typeDefs/dataTypes/panelAdminInput.graphql
src/graphql/typeDefs/dataTypes/regularAdminInput.graphql
src/graphql/typeDefs/dataTypes/workshopAdminInput.graphql
src/graphql/typeDefs/mutations/adminSession.graphql
src/graphql/typeDefs/mutations/adminSessionCreate.graphql
src/graphql/typeDefs/mutations/adminSessionUpdate.graphql
src/graphql/typeDefs/mutations/adminSessions.graphql
src/graphql/typeDefs/mutations/session.graphql
src/graphql/typeDefs/mutations/sessionCreate.graphql
src/graphql/typeDefs/mutations/sessionUpdate.graphql
src/graphql/typeDefs/mutations/sessions.graphql

Add update and create mutations for admin level only
moved admin delete and cancel from 'me' queries to admin path

admin mutations

---

src/graphql/resolvers/queries/acceptedSession.js
src/graphql/resolvers/queries/anonymizedSession.js
src/graphql/resolvers/queries/keynote.js
src/graphql/resolvers/queries/openSpace.js
src/graphql/resolvers/queries/panel.js
src/graphql/resolvers/queries/regular.js
src/graphql/resolvers/queries/theSessions.js
src/graphql/resolvers/queries/workshop.js

add tags to resolvers so nulls return as []

Fix no tags return null instead of []

---

src/graphql/typeDefs/dataTypes/interfaces/base.graphql
src/graphql/typeDefs/dataTypes/interfaces/eyesFront.graphql
src/graphql/typeDefs/dataTypes/session/keynote.graphql
src/graphql/typeDefs/dataTypes/session/openSpace.graphql
src/graphql/typeDefs/dataTypes/session/panel.graphql
src/graphql/typeDefs/dataTypes/session/regular.graphql
src/graphql/typeDefs/dataTypes/session/workshop.graphql

Adjusted order in type defs to help keep maintenance easier

move supportingArtifacts to Base interface

---

src/dataSources/cloudFirestore/session.js

It was quicker to add it then make a note :)

If session.startTime not in create, add it as null

---

package-lock.json
package.json
src/dataSources/cloudFirestore/__tests__/session.handleMentions.test.js
src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/mutations/sessionCreate.js

closes #99 
Has dependency on thatconference/that-api#34 to be published first.

adds mention parsing for communities

---

src/dataSources/cloudFirestore/session.js

add title to mention parsing

---

src/dataSources/cloudFirestore/session.js

add parsing of tags for mentions

---

package-lock.json
src/events/user.js
src/graphql/resolvers/mutations/adminSessionCreate.js
src/graphql/resolvers/mutations/adminSessionUpdate.js
src/graphql/resolvers/mutations/sessionCreate.js
src/graphql/resolvers/mutations/sessionUpdate.js

add event object to user event, passing to session create email and used for email type selection based on event.type
I figured since we have the event object as a reference now use it over the site information on the type of email to send.

add event object to user event,

---

package.json
src/events/user.js

fix email link bug.
Set api version from last update and this patch.1.4.0 -> 1.5.1.

 fix email link bug.

---

src/graphql/resolvers/queries/keynote.js
src/graphql/resolvers/queries/openSpace.js
src/graphql/resolvers/queries/panel.js
src/graphql/resolvers/queries/regular.js
src/graphql/resolvers/queries/workshop.js
src/graphql/typeDefs/dataTypes/interfaces/base.graphql
src/graphql/typeDefs/dataTypes/session/keynote.graphql
src/graphql/typeDefs/dataTypes/session/openSpace.graphql
src/graphql/typeDefs/dataTypes/session/panel.graphql
src/graphql/typeDefs/dataTypes/session/regular.graphql
src/graphql/typeDefs/dataTypes/session/workshop.graphql

I do ❤️ Apollo Federation at times :)

Add event type off of session types

---

src/graphql/resolvers/mutations/sessionUpdate.js

- clear protected fields from openspace to other type
- Add allow checks for event id changes on session types

clear protected fields from openspace to other type

---

package-lock.json
package.json
src/graphql/resolvers/mutations/sessionUpdate.js

Was setting value to empty string

Set location to null when cleared

---

package.json
src/events/admin.js
src/graphql/typeDefs/dataTypes/admin/keynoteAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/openSpaceAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/panelAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/regularAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/workshopAdminInput.graphql

Add tag and metadata to Postmark email request
Add needed fields for scheduling to admin inputs

postmark metadata and admin inputs

---

src/envConfig.js

Fix typo for base url

---

package.json
src/graphql/resolvers/mutations/sessionUpdate.js

set purge only on 'active' statuses

---

package.json
src/graphql/resolvers/mutations/adminSessionUpdate.js
src/graphql/resolvers/mutations/sessionUpdate.js

updates when graphCDN is purged on session update

---

package-lock.json
package.json
src/graphql/typeDefs/dataTypes/enums/targetLocation.graphql

v2.7.0
Schema change: TargetLocation. 
Audit fix a vuln
fixes #180

Schema change: TargetLocation

---

package-lock.json
package.json
src/dataSources/cloudFirestore/session.js
src/graphql/resolvers/queries/eventDestination.js
src/graphql/resolvers/queries/index.js
src/graphql/typeDefs/dataTypes/extendedTypes/extended-EventDestination.graphql

v2.9.0
Extends EventDestinationQuery type with a sessions field for that destination
minor package updates

Extends EventDestinationQuery type with a sessions field for that destination

---

package.json
src/graphql/typeDefs/dataTypes/enums/sessionLocationDestination.graphql

v2.12.0
Breaking change until events api is update as well thatconference/that-api-events#175

update room enum for Texas

---

package.json
src/graphql/typeDefs/dataTypes/enums/sessionLocationDestination.graphql

v2.13.0
Must be deployed with thatconference/that-api-events#176

forgot to add ranger station

---

package.json
src/graphql/typeDefs/dataTypes/admin/keynoteAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/openSpaceAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/panelAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/regularAdminInput.graphql
src/graphql/typeDefs/dataTypes/admin/workshopAdminInput.graphql

v3.5.1
Replace Slug Input type from `String` to `Slug`

Slugs are type Slug, not String

---

package-lock.json
package.json
src/graphql/index.js

v4.0.1
Refactor error reporting from Apollo server
minor package bumps

fix: refactor error reporting from apollo server

---

.env.sample
package.json
src/events/user.js

Remove references and calls to Orbit API calls

feat: remove all orbit api calls
